### PR TITLE
Feature/1132 rails assets migration

### LINKED ISSUE #1132: Move UX code to Rails assets
Taking a queue from the lessons learned from other projects we should move the frontend code into `app/assets`. The gulp, npm, and src directories should then be purged after the migration has been complete.

- Removes dependencies on the gulp build system
- Simpler development and deployment processes

Off the top of my head some things that will need to be refactored or worked around include
- Modules either need to be explicitly included before the rest of the app tree
- External vendor libraries will need to be added via rails-assets
  - Any vendor code not available will need to be placed into a vendor directory and then included into libraries
- Production Rails configs will need to be setup correctly to serve assets
- Productions deployments will need to include `rake assets:precompile` in place of all of the gulp and npm commands previously run.

### PR DESCRIPTION
**Pull request by AllenBW**
#### New Build Process
1. acquire dependencies `bundle install`
2. setup db `rake db:create` `rake db:setup` `rake sample:demo`
3. set your environment `RAILS_ENV= (production, development, test)`
4. precompile assets for the environment `rake assets:precompile`
5. start the server `rails s`

### Description
Swaps npm for rails, gulp for rails asset bridge and refactors structural layout of the frontend.
Minimal touch was applied to frontend, likely bugs that existed before still exist.
Updates a number of in place gems for compatibility. 

### Related Issue
closes #1132

### How Has This Been Tested?
existing tests pass, rspec

### Screenshots (if appropriate):
unmagled compiled code using env production and app working
screen shot 2016-04-19 at 11 42 10 am

screen shot 2016-04-19 at 12 01 12 pm
screen shot 2016-04-19 at 12 00 51 pm
screen shot 2016-04-19 at 12 00 43 pm

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Adds database migrations (Requires all environments to run `rake db:migrate` to work)
- [x] Adds new Gemfile dependencies (Requires all environments to run `bundle install` to work)
- [ ] Adds new ENV variables (description of ENV and purpose is required in the above description)

### Checklist:

- [x] My code follows the code style of this project.
- [x] My code has been cleaned of commented, logging, and inline test code.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by stackus** [comment]
Getting errors about missing assets.
screen shot 2016-04-19 at 1 49 38 pm

**Comment by stackus** [comment]
The template cache is not working. Requests are made for each template.

screen shot 2016-04-19 at 1 55 59 pm

**Comment by stackus** [comment]
Missing assets. These were found by mousing over the sidebar.

screen shot 2016-04-19 at 1 57 09 pm

**Comment by AllenBW** [comment]
yep a few lingering ones, addressed.

**Comment by chriskacerguis** [comment]
@stackus @AllenBW ready to go with this one?

**Comment by AllenBW** [comment]
I CAN'T WAIT FOR THOSE THUMBS!!! yeah all good on my end.

**Pull request merged**
